architecture:
  blur_kernel_size: 0
  blur_sigma: 0
  embedding_dim: 64
  is_cross_attn: false
  mean_field_hidden: 32
  mean_field_time_embed_dim: 32
  momdel_name: afno
  n_channels: 1
  n_fno_layers: 4
  n_hmodes: 32
  n_stacked_networks: 2
  n_tmodes: 2
  n_trans_head: 8
  n_trans_hidden: 64
  n_trans_layers: 4
  n_wmodes: 64
  slice_num: 64
  trans_dropout: 0.0
  use_mean_field: none
dataset:
  dropout_probabilities:
  - 0.05
  - 0.04
  - 0.03
  - 0.02
  - 0.01
  embedding_generator: Voronoi
  future_prediction_range: null
  init_sensor_timeframes:
  - 0
  - 5
  - 10
  - 15
  - 20
  n_fullstate_timeframes_per_chunk: 1
  n_samplings_per_chunk: 1
  n_sensors: 128
  resolution:
  - 48
  - 128
  seed: 1
  sensor_generator: LHS
  write_to_disk: true
evaluate:
  from_checkpoint: d:\hj\Y-2 S-1\Programming Project\FlowNet-NEW\TurbulentFlow-MeanField\checkpoints_best\.checkpoints_02-T-AFNO_inside_config\afno17.pt
  init_fullstate_timeframes:
  - 12
  is_generate_plots: false
  is_load_sensor_pos: false
  n_dropout_sensors: 0
  noise_level: 0
inference:
  case_dir: data/test/case0041
  from_checkpoint: .checkpoints_patch4\afnonet2.pt
  n_dropout_sensors: 0
  noise_level: null
  out_resolution:
  - 140
  - 240
  reconstruction_timeframes:
  - 177.5
  sensor_position_path: tensors/test/sensor_positions/pos.pt
  sensor_timeframes:
  - 165
  - 170
  - 175
  - 180
  - 185
training:
  freeze_bias: false
  freeze_branchnets: false
  freeze_trunknets: false
  from_checkpoint: null
  learning_rate: 1e-4
  n_epochs: 100
  patience: 10
  save_frequency: 1
  tolerance: 0.0
  train_batch_size: 2
  val_batch_size: 2
